name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "."

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout v6.0.2
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Get Node.js version
        id: get-node-version
        run: |
          if [ -f "${{ env.BUILD_PATH }}/.node-version" ]; then
            echo version=`cat "${{ env.BUILD_PATH }}/.node-version"` >> $GITHUB_OUTPUT
          else
            echo Missing file: "${{ env.BUILD_PATH }}/.node-version"
            exit 1
          fi
      - name: Setup Node.js ${{ steps.get-node-version.outputs.version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.get-node-version.outputs.version }}
          cache: "npm"
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json
      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_PATH }}
      - name: Pre-build checks
        run: npm run check
      - name: Build
        run: npm run build --if-present
        working-directory: ${{ env.BUILD_PATH }}
      # - name: Test
      #   run: npm run test
      #   working-directory: ${{ env.BUILD_PATH }}
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
